### ISSUE TITLE
Template full URL paths

### ISSUE THREAD

**Issue by geospatial-jeff** [developmentseed/rio-viz#11]
I'd love to use the HTML templates in an external FastAPI app.  Problem is my urls are different than what is used by rio-viz, for example my tilejson url is `${api_endpoint}/cog/tilejson.json?${url_params}`.

There are only a handful of routes which are called (`point`, `tilejson`, and `metadata`) and templating the full url would allow the HTML to be more easily consumed by other applications without adding much complexity to rio-viz.

The caller would of course have to ensure the request parameters and output for a certain route are the same as rio-viz, but if your app didn't have similar requests/responses you probably wouldn't be trying to use the HTML templates to begin with.

**Comment by vincentsarago** [comment]
done in #15
