### ISSUE TITLE
mvt_encoder not defined

### ISSUE THREAD

**Issue by dzanaga** [developmentseed/rio-viz#21]
Hi,

I installed rio-viz with `pip install rio-viz`.

when running `rio viz --help` I get an error here: https://github.com/developmentseed/rio-viz/blob/master/rio_viz/app.py#L38

`mvt_encoder` is not defined if `rio_viz_mvt` is not installed.

**Comment by vincentsarago** [comment]
🤦 will fix, thanks for the issue!

**Comment by vincentsarago** [comment]
fixed in https://github.com/developmentseed/rio-viz/commit/3b157e8a125848b2baa5d6a5e8e2e6b98d4918d1 
shipped `0.4.3` which should be on pypi in couple minutes
